version: '2'
services:
  hecate:
    build: .
    expose: 
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: ["./target/release/hecate", "--database", "hecate:password@postgres:5432/hecatedb"]
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
